apiVersion: batch/v1
kind: Job
metadata:
  name: background-cpu-noise-limited
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: noise
        image: companycloud-shoplab:local
        imagePullPolicy: Never
        command: ["python", "-c"]
        args: ["import time, math; end=time.time()+300; x=0
while time.time()<end:
    x += sum(math.sqrt(i%100+1) for i in range(120000))
print(x)"]
        resources:
          requests: {cpu: "100m", memory: "64Mi"}
          limits: {cpu: "300m", memory: "128Mi"}
